name: health_companion
description: "Serene Clinical & Health Companion production-ready application with Omni AI Copilot."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.20.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.5
  crypto: ^3.0.7
  image_picker: ^1.2.3
  file_picker: ^13.0.0
  path_provider: ^2.1.6
  path: ^1.9.1
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
